move hlint & stylish-haskell scripts inside the workflow file

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -41,13 +41,20 @@ jobs:
 
     - name: ✍  Check hlint and stylish
       run: |
-        bash scripts/hlint.sh
-        bash scripts/stylish-haskell.sh
+        curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s .
+        curl -sSL https://raw.github.com/jaspervdj/stylish-haskell/master/scripts/latest.sh | sh -s $(find . -type f -name "*.hs" ! -path "*.stack-work*") -i
+        if [ -z "$(git status --porcelain)" ]; then
+            echo "No style errors detected."
+        else
+            echo "Style errors detected:"
+            git diff
+            exit 1
+        fi
 
     - name: 🔨 Build & Test
       run: |
         stack --no-terminal test --bench --no-run-benchmarks --haddock --no-haddock-deps --coverage
-        wget -O Makefile https://raw.githubusercontent.com/input-output-hk/adrestia/master/.coverage/Makefile
+        wget -O Makefile https://raw.githubusercontent.com/input-output-hk/adrestia/master/.haskell/coverage/Makefile
         mkdir -p .coverage && touch .coverage/template.overlay
         DESTDIR=dist/coverage make report  && DESTDIR=dist/coverage make badge
         PKG_NAME=$(cat *.cabal | grep "name:" | sed "s/name:\s*\(.*\)/\1/")
